apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: kube-prom-stack
    meta.helm.sh/release-namespace: observability
  creationTimestamp: "2024-10-23T05:54:21Z"
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: kube-prom-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 45.5.0
    chart: kube-prometheus-stack-45.5.0
    heritage: Helm
    release: kube-prom-stack
    self-monitor: "true"
  name: kube-prom-stack-kube-prome-prometheus
  namespace: observability
  resourceVersion: "130353"
  uid: 5a9a60bb-d61c-4dba-87a9-d8c13e07a7ce
spec:
  clusterIP: 10.152.183.30
  clusterIPs:
  - 10.152.183.30
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-web
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: kube-prom-stack-kube-prome-prometheus
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
