{
 "title": "Kubernetes pods-GPU monitor",
 "tags": [
  "kubernetes",
  "pod",
  "gpu-metrics"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "GPU Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "gpu memory in MB",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kube_pod_gpu_memory_used_MiB{}", "legendFormat": "{{pod_name}}" }
   ]
  },
  {
   "title": "no: GPUs used",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_used_gpu_id) by (pod_name, namespace)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "gpu usage in %",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 11, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_utilization_gpu_percent{}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "gpu_ids",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "kube_pod_used_gpu_id",
     "legendFormat": "{{pod_name, gpu, namespace, node_name}}"
    }
   ]
  },
  {
   "title": "PID ",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "kube_pod_running_gpu_pid{}", "legendFormat": "{{pod_name}}" }
   ]
  }
 ]
}